name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install
        run: npm ci
      - name: E2E
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run se2e
